### ISSUE TITLE
SupercolliderAU for...VST Windows

### ISSUE THREAD

**Issue by alfonso73** [supercollider/SuperColliderAU#1]
Hi all,
coming from this post in SC main github
 https://github.com/supercollider/supercollider/issues/3745

I wonder if a VST2/3 version of SupercolliderAU would be a practical project. Or at least wich kind of strategies are goin' on in SCAU and if they are viable for the Win/VST world.

thanks and all the best
a.

**Comment by g-roma** [comment]
Hi, I have some ideas about that, but it would not be SuperColliderAU any more, so I think it is best to close the issue here.

**Comment by alfonso73** [comment]
Thanks Gerard. Do you have some plan about it? If yes let me know if i can help. best
