### ISSUE TITLE
README should specify how to pass path to macOS SDK when building

### ISSUE THREAD

**Issue by catniptwinz** [supercollider/SuperColliderAU#13]
As of ffeded0 it's necessary to either pass -DCMAKE_OSX_SYSROOT=</path/to/sdk/> to cmake when building or to have previously exported $SDKROOT. This results from:

https://github.com/supercollider/SuperColliderAU/blob/ffeded044354d78ec9dd97aa1d2b129874917026/CMakeLists.txt#L198

If this is intended behavior, the build instructions in the README should be updated to reflect it.

**Comment by g-roma** [comment]
This does not seem necessary on 10.15 with Xcode 11.6, I'll try to test with some other system, but yes at least it could be a workaround for now.

**Comment by catniptwinz** [comment]
macOS 10.14.6 / Xcode 11.3.1 here.

I believe cmake falls back on $SDKROOT if CMAKE_OSX_SYSROOT is not set. I don't have a 10.15 install to test with, but it's worth checking whether you're exporting $SDKROOT somewhere else (e.g. a dotfile), just so we know whether that's something that would need to be included in the build instructions.

**Comment by g-roma** [comment]
yes I checked the environment variable is not defined in the shell that starts CMAKE

**Comment by dyfer** [comment]
I've had this problem with xcode 10 on macOS 10.13 as well

**Comment by g-roma** [comment]
I tried on a 10.14 machine and did not find this, I suspect this may be related to the installation of xcode-tools and having run xcode-select, I wonder what do you get if you run  `xcrun --show-sdk-path` ? 
Maybe tis is the way to get it in the travis 10.1 image as well: https://gist.github.com/McMartin/6a4d07baa8e7fd45b5c864cb67c12a9c

**Comment by catniptwinz** [comment]
> I suspect this may be related to the installation of xcode-tools and having run xcode-select, I wonder what do you get if you run `xcrun --show-sdk-path` ?

`/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` here, in case it helps. I had the command line tools installed for several years and a couple MacOS versions prior to installing XCode.app.
