### ISSUE TITLE
Validation fails when connecting SuperColliderAU to Logic Pro

### ISSUE THREAD

**Issue by ianring** [supercollider/SuperColliderAU#2]
After some troubleshooting to get a successful build, I copied the component as prescribed, and then opened Logic Pro to try it out. On startup, Logic complained of an invalid plugin. In the Logic Plugin Manager, I clicked to rescan the SCAU, and validation fails. 

There are several tests that pass, but many of them fail, all with this same error:

Couldn't read Plist File /Library/Audio/Plug-Ins/Components/SuperColliderAU.component/Contents/Resources/pluginSpec.plist

*** ERROR: open directory failed '/Library/Audio/Plug-Ins/Components/SuperColliderAU.component/Contents/Resources/synthdefs'

What should I do?

**Comment by g-roma** [comment]
Hi, I'd need more information on why this fails. Ideally you should try on the command line with auval. The messages about missing files are actually normal and not necessarily a sign that the plugin is not working, unless you need them for standalone plug-ins.
