### ISSUE TITLE
Improve documentation in README

### ISSUE THREAD

**Issue by ianring** [supercollider/SuperColliderAU#3]
The doc says "you first need to build SuperCollider itself in the usual way". What is that?

To aid someone who is approaching SuperCollider for the first time, we could be more explicit... I found that building from the submodule didn't work and after much trial and error I discovered that I had to git clone --recursive the master SuperCollider repo separately, then copy it into the /SupercolliderAU/supercollider folder. But maybe it's that which has caused other problems with the AU validation (see the other issue I opened). Suffice to say that getting this project to build the component, and be valid when built, has been an unsuccessful journey so far.

**Comment by g-roma** [comment]
Thanks for reporting, the Readme file has been updated now.
