### ISSUE TITLE
Build fails with CMake errors

### ISSUE THREAD

**Issue by aronco206** [supercollider/SuperColliderAU#4]
I was able to successfully build supercollider following your updated ReadMe, which I had never been able to do before. I am running mac OS Mojave. I made it to the next step, building supercolliderAU, but running "cmake .." yielded the following warnings and errors with a failed build:

Warning 1:
"CMake Warning at CMakeLists.txt:36 (find_package):
  By not providing "FindPthreads.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Pthreads",
  but CMake did not find one.

  Could not find a package configuration file provided by "Pthreads" with any
  of the following names:

    PthreadsConfig.cmake
    pthreads-config.cmake

  Add the installation prefix of "Pthreads" to CMAKE_PREFIX_PATH or set
  "Pthreads_DIR" to a directory containing one of the above files.  If
  "Pthreads" provides a separate development package or SDK, be sure it has
  been installed."

Warning 2:
"CMake Warning at CMakeLists.txt:37 (find_package):
  By not providing "FindSndfile.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Sndfile", but
  CMake did not find one.

  Could not find a package configuration file provided by "Sndfile" with any
  of the following names:

    SndfileConfig.cmake
    sndfile-config.cmake

  Add the installation prefix of "Sndfile" to CMAKE_PREFIX_PATH or set
  "Sndfile_DIR" to a directory containing one of the above files.  If
  "Sndfile" provides a separate development package or SDK, be sure it has
  been installed."

And then the fatal error:

"failed to find AudioUnit/AudioUnit.r
/Users/anthonyroncolato/supercolliderAU/Source/SuperColliderAU.r:20: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - SysError 2 during open of "AudioUnit/AudioUnit.r".
Fatal Error!
/Users/anthonyroncolato/supercolliderAU/Source/SuperColliderAU.r:20: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - Fatal Error, can't recover.
/Users/anthonyroncolato/supercolliderAU/Source/SuperColliderAU.r: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - Since errors occurred, /Users/anthonyroncolato/supercolliderAU/Resources/SuperColliderAU.rsrc's resource fork was not written."

Despite the error, I decided to run "make" anyway just to see what would happen. It generated the supercolliderAU.component package, but when tested in Logic, it failed to recognize the plugin (which seems to be expected at this point).

Please let me know if I need to provide any further documentation or information, I'm very new to GitHub. Thank you!

**Comment by g-roma** [comment]
Hi, this is a problem of the build process trying to support the deprecated component manager. It shuld be fine if you remove lines 179 and 199-213 of CMakeLists.txt. Unfortunately I don't have a Mojave machine at hand at the moment, but will fix soon.

**Comment by g-roma** [comment]
Actually I tried with a freshly installed Mojave machine and it builds out of the box. Maybe you need to install xcode command line tools ?
